user$
    // ...
    // mergeMap(query => ajax.getJSON(`https://api.github.com/search/users?q=${query}`))
    switchMap(query => ajax.getJSON(`https://api.github.com/search/users?q=${query}`))
    // ...
